# Generated by Django 5.0 on 2024-03-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.CharField(max_length=50),
        ),
    ]
