# Generated by Django 5.0 on 2024-03-15 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_author_img"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
    ]
