# Generated by Django 5.0 on 2024-03-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_author_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="eng_name",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(upload_to="avatars"),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_img",
            field=models.ImageField(upload_to="posts"),
        ),
    ]
