# Generated by Django 5.0 on 2024-03-19 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_category_eng_name_alter_author_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="main.category",
            ),
        ),
    ]
