# Generated by Django 5.0 on 2024-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_category_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(),
        ),
    ]
